# Generated by Django 5.2.6 on 2025-09-10 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='aprovado',
            field=models.BooleanField(default=False),
        ),
    ]
