# Generated by Django 5.2.6 on 2025-10-01 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_post_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='data_postagem',
            field=models.DateTimeField(auto_now_add=True, default='2020-01-01'),
            preserve_default=False,
        ),
    ]
